#!/usr/bin/env python

import os

import bs4
import xerox


def main():
    with open(os.environ['QUTE_HTML'], encoding='UTF-8') as file:
        soup = bs4.BeautifulSoup(file)

    urls = []
    for element in soup.select('#headlines-frame > .Selected'):
        urls.append(element.select_one('a')['href'])

    xerox.copy('\n'.join(urls))


if __name__ == '__main__':
    main()
